name: ghost
icon: ghost
title: Ghost

services:
- name: ghost
  title: Ghost
  service: ghost
  required: true
  main: true
  replicas: 1
  volumes:
  - name: content
    size: 20
  links:
  - name: db
    service: mysql
  - name: sendmail
    service: opensmtpd

- name: mysql
  title: MySQL
  service: mysql
  required: true
  replicas: 1
  volumes:
  - name: data
    size: 20

- name: opensmtpd
  title: OpenSMTPD
  service: opensmtpd
  required: true
  replicas: 1
